---

- name: Configure bridged traffic module
  template:
    src: "templates/k8s.conf.module"
    dest: "/etc/modules-load.d/k8s.conf"
    owner: root
    group: root

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Configure bridged traffic iptables
  template:
    src: "templates/k8s.conf.sysctl"
    dest: "/etc/sysctl.d/k8s.conf"
    owner: root
    group: root

- name: Enable IPv4 traffic fowarding
  copy:
    dest: "/etc/sysctl.conf"
    content: net.ipv4.ip_forward = 1 

- name: Apply the settings
  command: sysctl -p --system
