---

- name: deploy containerd
  become: true
  hosts: 
    - k8s-group
  roles:
    - { role: package-install, pkgs: ["yum-utils", "device-mapper-persistent-data", "lvm2", "python3", "python3-pip", "net-tools", "telnet", "nano", "vim" ] , tags: ["containerd_deploy"] }
    - { role: package-repo, 
        repo:
          [
                { "name" : "containerd", "url" : "https://download.docker.com/linux/centos/docker-ce.repo" }
          ],
          tags: ["containerd_deploy"]
      }
    - { role: package-install, pkgs: ["containerd.io"] , tags: ["containerd_deploy"] }
    - { role: configure-containerd, tags: ["containerd_config"] }  