---

#FIX THIS SHIT MAKE IT PULL CONFIG FROM VARS.YAML

all:
  children:
    gcloud-hosts:
      children:
        master-group:
          hosts:
            alma-master-node-1:
              ansible_hosts: ip
          vars:
            ansible_user: deploy
        worker-group:
          hosts:
            alma-worker-node-1:
              ansible_hosts: ip
            alma-worker-node-2:
              ansible_hosts: ip
          vars:
            ansible_user: deploy

