---

#FIX THIS SHIT MAKE IT PULL CONFIG FROM VARS.YAML

all:
  children:
    gcloud-hosts:
      children:
        master-group:
          hosts:
            alma-master-node-1:
              ansible_hosts: 34.118.31.67
          vars:
            ansible_user: deploy
        worker-group:
          hosts:
            alma-worker-node-1:
              ansible_hosts: 34.118.16.71
            alma-worker-node-2:
              ansible_hosts: 34.116.198.42
          vars:
            ansible_user: deploy

